# Gaussian Elimination

In [4]:
%%latex
$

A=
  \begin{bmatrix}
    2 & 1 & 5\\
    4 & 4 & -4\\
    1 & 3 & 1
  \end{bmatrix} \;
x = \begin{bmatrix}
    x_0 \\
    x_1 \\
    x_2
  \end{bmatrix} \;


b = \begin{bmatrix}
    8 \\
    4 \\
    5
  \end{bmatrix}

$



<IPython.core.display.Latex object>

In [9]:
%%latex
$

[A|b]=
\left[
  \begin{array} {ccc|c}
    2 & 1 & 5 & 8\\
    4 & 4 & -4 & 4\\
    1 & 3 & 1 & 5\\
  \end{array}
\right]

$


<IPython.core.display.Latex object>

In [1]:
import numpy as np

In [266]:
def gaussian_partial(A, b):
    
    n = A.shape[0]
    
    C=np.c_[A,b.reshape(-1,1)]
    
    flag = 0
    
    #column
    for i in range(n-1):
            
        max_c, chosen_k  = 0, i
        
        #find the pivot
        for k in range(i, n):
            if np.abs(C[k,i]) > max_c:
                max_c = np.abs(C[k,i])
                chosen_k = k
         
        #Check if the pivot is zero
        if max_c == 0:
            flag = 1
            break
        
        #interchange rows
        if chosen_k != i:
            #Swap 2 rows
            temp = C[i,:].copy()
            C[i,:] = C[chosen_k,:]
            C[chosen_k,:] = temp
    
        
        #row
        for j in range(i+1, n):
            
            c = C[j,i]/C[i,i]
            C[j,:] = C[j,:] - c*C[i,:]
            
    return C, flag
        

In [267]:
def backsubstitution(T):
    
    flag=0
    n = T.shape[0]
    X = np.zeros((n))
    if T[n-1,n-1] == 0:
        flag = 1
    
    else:
    
        X[n-1] = T[n-1,n]/T[n-1,n-1] 

        for i in range(n-2,-1,-1):
            #Sum in row i
            s = 0
            for j in range(i+1, n):
                s += T[i,j]*X[j]

            X[i] = (T[i,n] - s)/T[i,i]
    
    return X, flag

In [268]:
A = np.array([[2, 1, 5],
            [4, 4, -4],
            [1, 3, 1]])
b= np.array([8,4,5])

In [261]:
A

array([[ 2,  1,  5],
       [ 4,  4, -4],
       [ 1,  3,  1]])

In [262]:
b

array([8, 4, 5])

In [269]:
T, err = gaussian_partial(A,b)

if err:
    print('Not unique solution')
else:
    X, err = backsubstitution(T)
    if err:
        print('Not unique solution')
    else:
        print('Solution:', X)

Solution: [1. 1. 1.]


In [270]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [23]:
%%latex
$
height = x_0 \cdot diameter
$

<IPython.core.display.Latex object>

In [ ]:
x_2 = \frac{4-2}{2} = 1