In [3]:
import numpy as np

In [4]:
def findDet(A, total = 0):
    
    dim = A.shape[0]
    
    if dim == 2:
        det = A[0,0]*A[1,1] - A[1,0]*A[0,1]
        return det
    
    else:
     
        
        A1 = A.copy()

        #Delete the first row
        A1 = np.delete(A1,0,0)
        
        cols = A.shape[1]

        for i in range(cols):
        
        #Delete the column corresponding to the position of the element traversed

            A2 = np.delete(A1,i,1)

            total += (-1)**i * A[0,i] * findDet(A2)
            
    return total

In [20]:
def crammer(A, b):
    
    n = A.shape[0]
    X = np.zeros((n))
    
    D = findDet(A)
    
    for i in range(n):
        
        Ai = A.copy()
        Ai[:,i] = b
        
        Di = findDet(Ai)
        
        X[i] = Di/D
    
    return X

In [25]:
A = np.array([[1,1,0,3],
            [2,1,-1,1],
            [3,-1,-1,2],
            [-1,2,3,-1]])

b = np.array([4,1,-3,4])

print(A)
print(b)

[[ 1  1  0  3]
 [ 2  1 -1  1]
 [ 3 -1 -1  2]
 [-1  2  3 -1]]
[ 4  1 -3  4]


In [26]:
crammer(A, b)

array([-1.,  2.,  0.,  1.])

In [27]:
np.linalg.solve(A,b)

array([-1.00000000e+00,  2.00000000e+00, -1.48029737e-16,  1.00000000e+00])