In [15]:
import numpy as np
def polynomial(m,n,t,c):
    
    A = np.empty((m,n))
    for i in range(m):
        for j in range(n):
            A[i,j] = t[i]**(n)
    
    return A@c
    
    

In [16]:
import numpy as np
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
m, n = 10, 8
t = np.random.randint(0, 100, m)
t

array([63, 11, 26, 45, 20, 34, 36, 48, 38, 83])

In [18]:
c = np.random.randint(0,100,n)
c

array([77, 81, 82, 24, 35, 64, 34,  8])

In [20]:
polynomial(m, n, t, c)

array([1.00503091e+17, 8.68153468e+10, 8.45749612e+13, 6.81012578e+15,
       1.03680000e+13, 7.23246531e+14, 1.14254951e+15, 1.14126086e+16,
       1.76085582e+15, 9.12178354e+17])